name: Building Docker Image and deploying to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
     
    - name: Current pwd
      run: |
        echo "$PWD"

    - name: Login to DockerHub and Building/Pushing Docker Image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker images
        docker build -t ss /home/runner/work/TechSol/TechSol/server
        docker push "${{ secrets.DOCKER_USERNAME }}/server:v1"