name: Building Docker Image and deploying to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Building and Pushing Docker Image to DockerHub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/server:latest -f server/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/server:latest